name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      # This action adds MSBuild.exe to the PATH environment variable
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore NuGet packages
      run: nuget restore TestGitHubActions.sln

    - name: Build solution
      # Use msbuild.exe to build the solution in Release configuration
      run: |
        msbuild.exe TestGitHubActions.sln /p:Configuration=Release
    - name: Publish web application
      run: |
        msbuild.exe TestGitHubActions.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile="FolderProfile"
      env:
        # Example using a GitHub Secret for a sensitive variable
        FolderProfile: ${{ secrets.PUBLISH_PROFILE_XML }}
