name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      # This action adds MSBuild.exe to the PATH environment variable
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore NuGet packages
      run: nuget restore TestGitHubActions.sln

    - name: Build solution
      # Use msbuild.exe to build the solution in Release configuration
      run: |
        msbuild.exe TestGitHubActions.sln /p:Configuration=Release
    - name: Publish web application
      run: |
        msbuild.exe TestGitHubActions.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile="FolderProfile"
      env:
        # Example using a GitHub Secret for a sensitive variable
        FolderProfile: ${{ secrets.PUBLISH_PROFILE_XML }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-app-release
        path: bin\app.publish\

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3
      #with:
        #platforms: windows/amd64

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: |
            #your-dockerhub-username/your-app
            #ghcr.io/your-github-username/your-app
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=This is a test app to validat github acitons

    - name: Build and push
      uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
